name: AudioQueue
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: ""  # fill in your Team ID

targets:
  AudioQueue:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AudioQueue
    info:
      path: AudioQueue/Info.plist
      properties:
        UIBackgroundModes:
          - audio
        CFBundleDisplayName: Audio Queue
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: AudioQueue/AudioQueue.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.yourname.audioqueue
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourname.audioqueue
      SWIFT_VERSION: "5.9"
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: MediaPlayer.framework
      - sdk: SwiftData.framework

  ShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ShareExtension
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Add to Queue
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsText: 1
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.yourname.audioqueue
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourname.audioqueue.share
      SWIFT_VERSION: "5.9"
    dependencies:
      - target: AudioQueue
        embed: false
