name: AudioQueue
options:
  bundleIdPrefix: com.theowu
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: "theowu93@gmail.com"  # fill in your Team ID

schemes:
  AudioQueue:
    build:
      targets:
        AudioQueue: all
        ShareExtension: all
        AudioQueueTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AudioQueueTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  AudioQueue:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AudioQueue
    info:
      path: AudioQueue/Info.plist
      properties:
        UIBackgroundModes:
          - audio
        CFBundleDisplayName: Audio Queue
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: AudioQueue/AudioQueue.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.theowu.audioqueue
        com.apple.developer.applesignin:
          - Default
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.theowu.audioqueue
      SWIFT_VERSION: "5.9"
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: MediaPlayer.framework
      - sdk: AuthenticationServices.framework
      - sdk: WebKit.framework
      - target: ShareExtension

  ShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ShareExtension
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Add to Queue
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsText: true
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.theowu.audioqueue
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.theowu.audioqueue.share
      SWIFT_VERSION: "5.9"
    dependencies: []

  AudioQueueTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AudioQueueTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.theowu.audioqueue.tests
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AudioQueue
